#!/usr/bin/python3
import sys
from sys import argv


def factorize(value):
    
    """
    # Usage: factors <file>
    # Output format: n=p*q
    """
    
    i = 2

    if value < 2:
        return
    
    while value % i:
        i += 1
    print("{:.0f}={:.0f}*{:.0f}".format(value, value / i, i))


if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as file:
        line = file.readline()

        while line != "":
            value = int(line.split('\n')[0])
            factorize(value)
            line = file.readline()
except FileNotFoundError:
    print(f'File not found: {argv}')
except ValueError:
    print(f'Invalid input in the file: {argv}')
except Exception as e:
    print(f'An error occurred: {str(e)}')
    pass
