#!/usr/bin/python3
import sys
from sympy import factorint

def factorize_large_number(n):
    """
    Factorize a large number into prime factors.
    """
    factors = factorint(n)

    prime_factors = list(factors.keys())
    if len(prime_factors) == 2:
        p, q = prime_factors
        print(f"{n}={p}*{q}")
    else:
        print(f"{n} is not the product of exactly two prime numbers.")

if len(sys.argv) != 2:
    print("Usage: ./rsa <file>")
    sys.exit(1)

try:
    with open(sys.argv[1]) as file:
        line = file.readline()

        while line:
            n = int(line.strip())
            factorize_large_number(n)
            line = file.readline()

except FileNotFoundError:
    print(f'File not found: {sys.argv[1]}')
except ValueError:
    print(f'Invalid input in the file: {sys.argv[1]}')
except Exception as e:
    print(f'An error occurred: {str(e)}')
    pass

